apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  template:
    metadata:
      name: pod-javadb-prd
      labels:
        app: pod-javadb-prd
    spec:
      containers:
        - name: container-pod-javadb-prd
          image: celo/projeto_final:0.0.2
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-prd
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-prd
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadb-prd
